/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FC0_RXD_SDA_MOSI_DATA (coord H16), J45[22]/U9[13]/U105[4]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITUARTPINS_DEBUG_UART_RX_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define BOARD_INITUARTPINS_DEBUG_UART_RX_SIGNAL RXD_SDA_MOSI_DATA
/* @} */

/*! @name FC0_TXD_SCL_MISO_WS (coord G16), J45[32]/U105[3]/U9[12]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITUARTPINS_DEBUG_UART_TXD_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define BOARD_INITUARTPINS_DEBUG_UART_TXD_SIGNAL TXD_SCL_MISO_WS
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUARTPins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FULLDRIVE_EN 0x0100u   /*!<@brief Full drive enable */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_FUNC8 0x08u            /*!<@brief Selects pin function 8 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PULLUP_EN 0x20u        /*!<@brief Enable pull-up function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_PUPD_EN 0x10u          /*!<@brief Enable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */
#define IOPCTL_PIO_SLEW_RATE_SLOW 0x80u   /*!<@brief Slow mode */

/*! @name FC4_RXD_SDA_MOSI_DATA (coord D14), J45[58]/I2C_SDA/U6[6]/ACC_I2C_SDA
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_ACC_I2C_SDA_PERIPHERAL FLEXCOMM4
/*!
 * @brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_ACC_I2C_SDA_SIGNAL RXD_SDA_MOSI_DATA
/* @} */

/*! @name FC4_TXD_SCL_MISO_WS (coord B11), J45[60]/I2C_SCL/U6[4]/ACC_I2C_SCL
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_ACC_I2C_SCL_PERIPHERAL FLEXCOMM4
/*!
 * @brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_ACC_I2C_SCL_SIGNAL TXD_SCL_MISO_WS
/* @} */

/*! @name FLEXIO_D0 (coord R8), J27[3]/J43[13]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_FXIO_D0_PERIPHERAL FLEXIO0     /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_FXIO_D0_SIGNAL IO              /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_FXIO_D0_CHANNEL 0              /*!<@brief Signal channel */
                                                                 /* @} */

/*! @name FLEXIO_D1 (coord P10), J28[10]/J30[6]/J43[14]/FXIO_D1
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_D1_PERIPHERAL FLEXIO0
/*!
 * @brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_D1_SIGNAL IO
/*!
 * @brief Signal channel */
#define BOARD_INITFLEXIOPANELPINS_D1_CHANNEL 1
/* @} */

/*! @name FLEXIO_D2 (coord U10), J28[9]/J30[5]/J43[15]/FXIO_D2
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_D2_PERIPHERAL FLEXIO0
/*!
 * @brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_D2_SIGNAL IO
/*!
 * @brief Signal channel */
#define BOARD_INITFLEXIOPANELPINS_D2_CHANNEL 2
/* @} */

/*! @name FLEXIO_D3 (coord T8), J27[4]/J43[16]/FXIO_D3
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_D3_PERIPHERAL FLEXIO0             /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_D3_SIGNAL IO                      /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_D3_CHANNEL 3                      /*!<@brief Signal channel */
                                                                    /* @} */

/*! @name FLEXIO_D4 (coord T10), J27[5]/J43[17]/FXIO_D4
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_D4_PERIPHERAL FLEXIO0             /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_D4_SIGNAL IO                      /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_D4_CHANNEL 4                      /*!<@brief Signal channel */
                                                                    /* @} */

/*! @name FLEXIO_D5 (coord T11), J27[6]/J43[18]/FXIO_D5
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_D5_PERIPHERAL FLEXIO0             /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_D5_SIGNAL IO                      /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_D5_CHANNEL 5                      /*!<@brief Signal channel */
                                                                    /* @} */

/*! @name FLEXIO_D6 (coord T12), J27[7]/J43[19]/FXIO_D6
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_D6_PERIPHERAL FLEXIO0             /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_D6_SIGNAL IO                      /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_D6_CHANNEL 6                      /*!<@brief Signal channel */
                                                                    /* @} */

/*! @name FLEXIO_D7 (coord P9), J27[8]/J43[20]/FXIO_D7
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_D7_PERIPHERAL FLEXIO0             /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_D7_SIGNAL IO                      /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_D7_CHANNEL 7                      /*!<@brief Signal channel */
                                                                    /* @} */

/*! @name FLEXIO_D14 (coord R9), J28[5]/J43[10]/FXIO_D14
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_WR_PERIPHERAL FLEXIO0              /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_WR_SIGNAL IO                       /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_WR_CHANNEL 14                      /*!<@brief Signal channel */
                                                                     /* @} */

/*! @name FLEXIO_D15 (coord R10), J28[6]/J43[11]/FXIO_D15
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_RD_PERIPHERAL FLEXIO0              /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_RD_SIGNAL IO                       /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_RD_CHANNEL 15                      /*!<@brief Signal channel */
                                                                     /* @} */

/*! @name PIO5_1 (coord M9), J28[4]/J43[9]/FXIO_D13
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_CS_PERIPHERAL GPIO                /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_CS_SIGNAL PIO5                    /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_CS_CHANNEL 1                      /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITFLEXIOPANELPINS_CS_GPIO GPIO                      /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITFLEXIOPANELPINS_CS_GPIO_PIN_MASK (1U << 1U)       /*!<@brief GPIO pin mask */
#define BOARD_INITFLEXIOPANELPINS_CS_PORT 5U                        /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXIOPANELPINS_CS_PIN 1U                         /*!<@brief PORT pin number */
#define BOARD_INITFLEXIOPANELPINS_CS_PIN_MASK (1U << 1U)            /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PIO5_0 (coord P12), J28[3]/J43[7]/FXIO_D12
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_RST_PERIPHERAL GPIO                /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_RST_SIGNAL PIO5                    /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_RST_CHANNEL 0                      /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITFLEXIOPANELPINS_RST_GPIO GPIO                      /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITFLEXIOPANELPINS_RST_GPIO_PIN_MASK (1U << 0U)       /*!<@brief GPIO pin mask */
#define BOARD_INITFLEXIOPANELPINS_RST_PORT 5U                        /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXIOPANELPINS_RST_PIN 0U                         /*!<@brief PORT pin number */
#define BOARD_INITFLEXIOPANELPINS_RST_PIN_MASK (1U << 0U)            /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name PIO4_31 (coord N10), J27[1]/J43[8]/FXIO_D11
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXIOPANELPINS_D11_PERIPHERAL GPIO                /*!<@brief Peripheral name */
#define BOARD_INITFLEXIOPANELPINS_D11_SIGNAL PIO4                    /*!<@brief Signal name */
#define BOARD_INITFLEXIOPANELPINS_D11_CHANNEL 31                     /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITFLEXIOPANELPINS_D11_GPIO GPIO                      /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITFLEXIOPANELPINS_D11_GPIO_PIN_MASK (1U << 31U)      /*!<@brief GPIO pin mask */
#define BOARD_INITFLEXIOPANELPINS_D11_PORT 4U                        /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXIOPANELPINS_D11_PIN 31U                        /*!<@brief PORT pin number */
#define BOARD_INITFLEXIOPANELPINS_D11_PIN_MASK (1U << 31U)           /*!<@brief PORT pin mask */
                                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFlexIOPanelPins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_EN 0x0100u   /*!<@brief Full drive enable */
#define IOPCTL_PIO_FUNC2 0x02u            /*!<@brief Selects pin function 2 */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_PUPD_EN 0x10u          /*!<@brief Enable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FLEXSPI1_SCLK (coord H2), U108[B2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_CLK_PERIPHERAL FLEXSPI1    /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_CLK_SIGNAL FLEXSPI_SCLK    /*!<@brief Signal name */
                                                             /* @} */

/*! @name FLEXSPI1_DATA0 (coord H1), U108[D3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ0_PERIPHERAL FLEXSPI1     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ0_SIGNAL FLEXSPI_DATA0    /*!<@brief Signal name */
                                                               /* @} */

/*! @name FLEXSPI1_DATA1 (coord G2), U108[D2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ1_PERIPHERAL FLEXSPI1     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ1_SIGNAL FLEXSPI_DATA1    /*!<@brief Signal name */
                                                               /* @} */

/*! @name FLEXSPI1_DATA2 (coord F1), U108[C4]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ2_PERIPHERAL FLEXSPI1     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ2_SIGNAL FLEXSPI_DATA2    /*!<@brief Signal name */
                                                               /* @} */

/*! @name FLEXSPI1_DATA3 (coord K3), U108[D4]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ3_PERIPHERAL FLEXSPI1     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ3_SIGNAL FLEXSPI_DATA3    /*!<@brief Signal name */
                                                               /* @} */

/*! @name FLEXSPI1_DATA4 (coord H5), U108[D5]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ4_PERIPHERAL FLEXSPI1     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ4_SIGNAL FLEXSPI_DATA4    /*!<@brief Signal name */
                                                               /* @} */

/*! @name FLEXSPI1_DATA5 (coord H4), U108[E3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ5_PERIPHERAL FLEXSPI1     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ5_SIGNAL FLEXSPI_DATA5    /*!<@brief Signal name */
                                                               /* @} */

/*! @name FLEXSPI1_DATA6 (coord J3), U108[E2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ6_PERIPHERAL FLEXSPI1     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ6_SIGNAL FLEXSPI_DATA6    /*!<@brief Signal name */
                                                               /* @} */

/*! @name FLEXSPI1_DATA7 (coord J4), U108[E1]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ7_PERIPHERAL FLEXSPI1     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ7_SIGNAL FLEXSPI_DATA7    /*!<@brief Signal name */
                                                               /* @} */

/*! @name FLEXSPI1_DQS (coord H3), U108[C3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_DQS_PERIPHERAL FLEXSPI1   /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_DQS_SIGNAL FLEXSPI_DQS    /*!<@brief Signal name */
                                                            /* @} */

/*! @name FLEXSPI1_SS0_N (coord E13), U108[A3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_CE_PERIPHERAL FLEXSPI1     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_CE_SIGNAL FLEXSPI_SS0_N    /*!<@brief Signal name */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPsRamPins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PULLUP_EN 0x20u        /*!<@brief Enable pull-up function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_PUPD_EN 0x10u          /*!<@brief Enable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name PIO0_12 (coord E14), U44[5]/LCM_BL_PWM_1V8
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITMIPIPANELPINS_LCM_BL_PWM_PERIPHERAL GPIO
/*!
 * @brief Signal name */
#define BOARD_INITMIPIPANELPINS_LCM_BL_PWM_SIGNAL PIO0
/*!
 * @brief Signal channel */
#define BOARD_INITMIPIPANELPINS_LCM_BL_PWM_CHANNEL 12

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_BL_PWM_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITMIPIPANELPINS_LCM_BL_PWM_GPIO_PIN_MASK (1U << 12U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_BL_PWM_PORT 0U
/*!
 * @brief PORT pin number */
#define BOARD_INITMIPIPANELPINS_LCM_BL_PWM_PIN 12U
/*!
 * @brief PORT pin mask */
#define BOARD_INITMIPIPANELPINS_LCM_BL_PWM_PIN_MASK (1U << 12U)
/* @} */

/*! @name PIO3_21 (coord E5), J44[21]/LCM_RESET_B
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITMIPIPANELPINS_LCM_RESET_B_PERIPHERAL GPIO
/*!
 * @brief Signal name */
#define BOARD_INITMIPIPANELPINS_LCM_RESET_B_SIGNAL PIO3
/*!
 * @brief Signal channel */
#define BOARD_INITMIPIPANELPINS_LCM_RESET_B_CHANNEL 21

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_RESET_B_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITMIPIPANELPINS_LCM_RESET_B_GPIO_PIN_MASK (1U << 21U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_RESET_B_PORT 3U
/*!
 * @brief PORT pin number */
#define BOARD_INITMIPIPANELPINS_LCM_RESET_B_PIN 21U
/*!
 * @brief PORT pin mask */
#define BOARD_INITMIPIPANELPINS_LCM_RESET_B_PIN_MASK (1U << 21U)
/* @} */

/*! @name PIO3_15 (coord E10), U44[4]/LCM_PWR_EN
  @{ */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_LCM_PWR_EN_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define BOARD_INITMIPIPANELPINS_LCM_PWR_EN_SIGNAL PIO3               /*!<@brief Signal name */
#define BOARD_INITMIPIPANELPINS_LCM_PWR_EN_CHANNEL 15                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_LCM_PWR_EN_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_PWR_EN_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */
#define BOARD_INITMIPIPANELPINS_LCM_PWR_EN_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_PWR_EN_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITMIPIPANELPINS_LCM_PWR_EN_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name FC4_RXD_SDA_MOSI_DATA (coord D14), J45[58]/I2C_SDA/U6[6]/ACC_I2C_SDA
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITMIPIPANELPINS_ACC_I2C_SDA_PERIPHERAL FLEXCOMM4
/*!
 * @brief Signal name */
#define BOARD_INITMIPIPANELPINS_ACC_I2C_SDA_SIGNAL RXD_SDA_MOSI_DATA
/* @} */

/*! @name FC4_TXD_SCL_MISO_WS (coord B11), J45[60]/I2C_SCL/U6[4]/ACC_I2C_SCL
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITMIPIPANELPINS_ACC_I2C_SCL_PERIPHERAL FLEXCOMM4
/*!
 * @brief Signal name */
#define BOARD_INITMIPIPANELPINS_ACC_I2C_SCL_SIGNAL TXD_SCL_MISO_WS
/* @} */

/*! @name PIO4_4 (coord P17), U44[3]/LCM_CTP_RST_1V8
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_RST_B_PERIPHERAL GPIO
/*!
 * @brief Signal name */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_RST_B_SIGNAL PIO4
/*!
 * @brief Signal channel */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_RST_B_CHANNEL 4

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_RST_B_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_RST_B_GPIO_PIN_MASK (1U << 4U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_RST_B_PORT 4U
/*!
 * @brief PORT pin number */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_RST_B_PIN 4U
/*!
 * @brief PORT pin mask */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_RST_B_PIN_MASK (1U << 4U)
/* @} */

/*! @name PIO3_19 (coord C6), U44[6]/LCM_CTP_INT_1V8
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_INT_PERIPHERAL GPIO
/*!
 * @brief Signal name */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_INT_SIGNAL PIO3
/*!
 * @brief Signal channel */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_INT_CHANNEL 19

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_INT_GPIO GPIO
/*!
 * @brief GPIO pin mask */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_INT_GPIO_PIN_MASK (1U << 19U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_INT_PORT 3U
/*!
 * @brief PORT pin number */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_INT_PIN 19U
/*!
 * @brief PORT pin mask */
#define BOARD_INITMIPIPANELPINS_LCM_CTP_INT_PIN_MASK (1U << 19U)
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMipiPanelPins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name PIO0_14 (coord B12), Q3[2]/PWM_RED_LED
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LED_RED_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define BOARD_INITPINS_LED_RED_SIGNAL PIO0               /*!<@brief Signal name */
#define BOARD_INITPINS_LED_RED_CHANNEL 14                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_RED_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_RED_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_10 (coord K16), USER_KEY2
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_SW2_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define BOARD_INITPINS_SW2_SIGNAL PIO0               /*!<@brief Signal name */
#define BOARD_INITPINS_SW2_CHANNEL 10                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW2_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_SW2_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW2_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW2_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_25 (coord C12), USER_KEY1
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_SW1_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define BOARD_INITPINS_SW1_SIGNAL PIO0               /*!<@brief Signal name */
#define BOARD_INITPINS_SW1_CHANNEL 25                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW1_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_SW1_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW1_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW1_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
